### ISSUE TITLE
ffxiv.auto.translate.en.cs

### ISSUE THREAD

**Issue by xDarkOne** [3735943886/FfxivTool#1]
Hello.
I found your file here - https://gist.github.com/3735943886/fe5ac8012ffe37c9dfa180b1944b513c
And wanted to ask you.
How did you get it, find out the IDs, etc. I want to make an actual version for patch 5.2.
Thank you!

**Comment by 3735943886** [comment]
In my case, I created simple App that send keystroke to ffxiv client.
It was log time ago, and I cannot remember clearly but, the keystroke app send key sequences like "tab down enter, tab down down enter, tab down(x3) enter, ..." and created all logs of ffxiv auto-translation dictionary.
And you can find many ffxiv tools that analyze ffxiv logs.
Using one of ffxiv log analyzer, you can get IDs of ffxiv auto-translation dictionary.

**Comment by xDarkOne** [comment]
Thank you for your answer!
